//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Infrastructure.FirmaElock {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.soap.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.soap.com/")]
    public partial class signFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorField;
        
        private byte[] messageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.soap.com/", ConfigurationName="FirmaElock.SignFileImpl")]
    public interface SignFileImpl {
        
        // CODEGEN: Parameter 'inputfile' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.soap.com/SignFileImpl/SignFileRequest", ReplyAction="http://impl.soap.com/SignFileImpl/SignFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(App.Infrastructure.FirmaElock.Exception), Action="http://impl.soap.com/SignFileImpl/SignFile/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        App.Infrastructure.FirmaElock.SignFileResponse1 SignFile(App.Infrastructure.FirmaElock.SignFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.soap.com/SignFileImpl/SignFileRequest", ReplyAction="http://impl.soap.com/SignFileImpl/SignFileResponse")]
        System.Threading.Tasks.Task<App.Infrastructure.FirmaElock.SignFileResponse1> SignFileAsync(App.Infrastructure.FirmaElock.SignFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.soap.com/SignFileImpl/SignBase64EncodedRequest", ReplyAction="http://impl.soap.com/SignFileImpl/SignBase64EncodedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(App.Infrastructure.FirmaElock.Exception), Action="http://impl.soap.com/SignFileImpl/SignBase64Encoded/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        App.Infrastructure.FirmaElock.signBase64EncodedResponse SignBase64Encoded(string inputfile, string signer_name, string position, string pagenumber, string reason, string location, int xmargin, int ymargin, int height, int width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.soap.com/SignFileImpl/SignBase64EncodedRequest", ReplyAction="http://impl.soap.com/SignFileImpl/SignBase64EncodedResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<App.Infrastructure.FirmaElock.signBase64EncodedResponse> SignBase64EncodedAsync(string inputfile, string signer_name, string position, string pagenumber, string reason, string location, int xmargin, int ymargin, int height, int width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.soap.com/SignFileImpl/getSignerNameListRequest", ReplyAction="http://impl.soap.com/SignFileImpl/getSignerNameListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        App.Infrastructure.FirmaElock.signerInfo getSignerNameList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.soap.com/SignFileImpl/getSignerNameListRequest", ReplyAction="http://impl.soap.com/SignFileImpl/getSignerNameListResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<App.Infrastructure.FirmaElock.signerInfo> getSignerNameListAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignFile", WrapperNamespace="http://impl.soap.com/", IsWrapped=true)]
    public partial class SignFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] inputfile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string signer_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string position;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string pagenumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string location;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int xmargin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int ymargin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int height;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int width;
        
        public SignFileRequest() {
        }
        
        public SignFileRequest(byte[] inputfile, string signer_name, string position, string pagenumber, string reason, string location, int xmargin, int ymargin, int height, int width) {
            this.inputfile = inputfile;
            this.signer_name = signer_name;
            this.position = position;
            this.pagenumber = pagenumber;
            this.reason = reason;
            this.location = location;
            this.xmargin = xmargin;
            this.ymargin = ymargin;
            this.height = height;
            this.width = width;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignFileResponse", WrapperNamespace="http://impl.soap.com/", IsWrapped=true)]
    public partial class SignFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public App.Infrastructure.FirmaElock.signFileResponse @return;
        
        public SignFileResponse1() {
        }
        
        public SignFileResponse1(App.Infrastructure.FirmaElock.signFileResponse @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.soap.com/")]
    public partial class signBase64EncodedResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorField;
        
        private string messageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.soap.com/")]
    public partial class signerInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorField;
        
        private string[] signerField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("signer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] signer {
            get {
                return this.signerField;
            }
            set {
                this.signerField = value;
                this.RaisePropertyChanged("signer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SignFileImplChannel : App.Infrastructure.FirmaElock.SignFileImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignFileImplClient : System.ServiceModel.ClientBase<App.Infrastructure.FirmaElock.SignFileImpl>, App.Infrastructure.FirmaElock.SignFileImpl {
        
        public SignFileImplClient() {
        }
        
        public SignFileImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignFileImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignFileImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignFileImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Infrastructure.FirmaElock.SignFileResponse1 App.Infrastructure.FirmaElock.SignFileImpl.SignFile(App.Infrastructure.FirmaElock.SignFileRequest request) {
            return base.Channel.SignFile(request);
        }
        
        public App.Infrastructure.FirmaElock.signFileResponse SignFile(byte[] inputfile, string signer_name, string position, string pagenumber, string reason, string location, int xmargin, int ymargin, int height, int width) {
            App.Infrastructure.FirmaElock.SignFileRequest inValue = new App.Infrastructure.FirmaElock.SignFileRequest();
            inValue.inputfile = inputfile;
            inValue.signer_name = signer_name;
            inValue.position = position;
            inValue.pagenumber = pagenumber;
            inValue.reason = reason;
            inValue.location = location;
            inValue.xmargin = xmargin;
            inValue.ymargin = ymargin;
            inValue.height = height;
            inValue.width = width;
            App.Infrastructure.FirmaElock.SignFileResponse1 retVal = ((App.Infrastructure.FirmaElock.SignFileImpl)(this)).SignFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Infrastructure.FirmaElock.SignFileResponse1> App.Infrastructure.FirmaElock.SignFileImpl.SignFileAsync(App.Infrastructure.FirmaElock.SignFileRequest request) {
            return base.Channel.SignFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Infrastructure.FirmaElock.SignFileResponse1> SignFileAsync(byte[] inputfile, string signer_name, string position, string pagenumber, string reason, string location, int xmargin, int ymargin, int height, int width) {
            App.Infrastructure.FirmaElock.SignFileRequest inValue = new App.Infrastructure.FirmaElock.SignFileRequest();
            inValue.inputfile = inputfile;
            inValue.signer_name = signer_name;
            inValue.position = position;
            inValue.pagenumber = pagenumber;
            inValue.reason = reason;
            inValue.location = location;
            inValue.xmargin = xmargin;
            inValue.ymargin = ymargin;
            inValue.height = height;
            inValue.width = width;
            return ((App.Infrastructure.FirmaElock.SignFileImpl)(this)).SignFileAsync(inValue);
        }
        
        public App.Infrastructure.FirmaElock.signBase64EncodedResponse SignBase64Encoded(string inputfile, string signer_name, string position, string pagenumber, string reason, string location, int xmargin, int ymargin, int height, int width) {
            return base.Channel.SignBase64Encoded(inputfile, signer_name, position, pagenumber, reason, location, xmargin, ymargin, height, width);
        }
        
        public System.Threading.Tasks.Task<App.Infrastructure.FirmaElock.signBase64EncodedResponse> SignBase64EncodedAsync(string inputfile, string signer_name, string position, string pagenumber, string reason, string location, int xmargin, int ymargin, int height, int width) {
            return base.Channel.SignBase64EncodedAsync(inputfile, signer_name, position, pagenumber, reason, location, xmargin, ymargin, height, width);
        }
        
        public App.Infrastructure.FirmaElock.signerInfo getSignerNameList() {
            return base.Channel.getSignerNameList();
        }
        
        public System.Threading.Tasks.Task<App.Infrastructure.FirmaElock.signerInfo> getSignerNameListAsync() {
            return base.Channel.getSignerNameListAsync();
        }
    }
}
