//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Infrastructure.HSMService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncabezadoRequest", Namespace="http://www.e-sign.cl/")]
    [System.SerializableAttribute()]
    public partial class EncabezadoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoIntercambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreConfiguracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaEsperadaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoIntercambio {
            get {
                return this.TipoIntercambioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoIntercambioField, value) != true)) {
                    this.TipoIntercambioField = value;
                    this.RaisePropertyChanged("TipoIntercambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NombreConfiguracion {
            get {
                return this.NombreConfiguracionField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreConfiguracionField, value) != true)) {
                    this.NombreConfiguracionField = value;
                    this.RaisePropertyChanged("NombreConfiguracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FormatoDocumento {
            get {
                return this.FormatoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatoDocumentoField, value) != true)) {
                    this.FormatoDocumentoField = value;
                    this.RaisePropertyChanged("FormatoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RespuestaEsperada {
            get {
                return this.RespuestaEsperadaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaEsperadaField, value) != true)) {
                    this.RespuestaEsperadaField = value;
                    this.RaisePropertyChanged("RespuestaEsperada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoParametro", Namespace="http://www.e-sign.cl/")]
    [System.SerializableAttribute()]
    public partial class DocumentoParametro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreDocumento {
            get {
                return this.NombreDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDocumentoField, value) != true)) {
                    this.NombreDocumentoField = value;
                    this.RaisePropertyChanged("NombreDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MetaData {
            get {
                return this.MetaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDataField, value) != true)) {
                    this.MetaDataField = value;
                    this.RaisePropertyChanged("MetaData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncabezadoResponse", Namespace="http://www.e-sign.cl/")]
    [System.SerializableAttribute()]
    public partial class EncabezadoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FormatoDocumento {
            get {
                return this.FormatoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatoDocumentoField, value) != true)) {
                    this.FormatoDocumentoField = value;
                    this.RaisePropertyChanged("FormatoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NombreDocumento {
            get {
                return this.NombreDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDocumentoField, value) != true)) {
                    this.NombreDocumentoField = value;
                    this.RaisePropertyChanged("NombreDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.e-sign.cl/", ConfigurationName="HSMService.WSIntercambiaDocSoap")]
    public interface WSIntercambiaDocSoap {
        
        // CODEGEN: Generating message contract since element name Encabezado from namespace http://www.e-sign.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-sign.cl/IntercambiaDoc", ReplyAction="*")]
        App.Infrastructure.HSMService.IntercambiaDocResponse IntercambiaDoc(App.Infrastructure.HSMService.IntercambiaDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-sign.cl/IntercambiaDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Infrastructure.HSMService.IntercambiaDocResponse> IntercambiaDocAsync(App.Infrastructure.HSMService.IntercambiaDocRequest request);
        
        // CODEGEN: Generating message contract since element name MantencionDeSistemaResult from namespace http://www.e-sign.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-sign.cl/MantencionDeSistema", ReplyAction="*")]
        App.Infrastructure.HSMService.MantencionDeSistemaResponse MantencionDeSistema(App.Infrastructure.HSMService.MantencionDeSistemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-sign.cl/MantencionDeSistema", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Infrastructure.HSMService.MantencionDeSistemaResponse> MantencionDeSistemaAsync(App.Infrastructure.HSMService.MantencionDeSistemaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IntercambiaDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IntercambiaDoc", Namespace="http://www.e-sign.cl/", Order=0)]
        public App.Infrastructure.HSMService.IntercambiaDocRequestBody Body;
        
        public IntercambiaDocRequest() {
        }
        
        public IntercambiaDocRequest(App.Infrastructure.HSMService.IntercambiaDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.e-sign.cl/")]
    public partial class IntercambiaDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Infrastructure.HSMService.EncabezadoRequest Encabezado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public App.Infrastructure.HSMService.DocumentoParametro Parametro;
        
        public IntercambiaDocRequestBody() {
        }
        
        public IntercambiaDocRequestBody(App.Infrastructure.HSMService.EncabezadoRequest Encabezado, App.Infrastructure.HSMService.DocumentoParametro Parametro) {
            this.Encabezado = Encabezado;
            this.Parametro = Parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IntercambiaDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IntercambiaDocResponse", Namespace="http://www.e-sign.cl/", Order=0)]
        public App.Infrastructure.HSMService.IntercambiaDocResponseBody Body;
        
        public IntercambiaDocResponse() {
        }
        
        public IntercambiaDocResponse(App.Infrastructure.HSMService.IntercambiaDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.e-sign.cl/")]
    public partial class IntercambiaDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Infrastructure.HSMService.EncabezadoResponse IntercambiaDocResult;
        
        public IntercambiaDocResponseBody() {
        }
        
        public IntercambiaDocResponseBody(App.Infrastructure.HSMService.EncabezadoResponse IntercambiaDocResult) {
            this.IntercambiaDocResult = IntercambiaDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MantencionDeSistemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MantencionDeSistema", Namespace="http://www.e-sign.cl/", Order=0)]
        public App.Infrastructure.HSMService.MantencionDeSistemaRequestBody Body;
        
        public MantencionDeSistemaRequest() {
        }
        
        public MantencionDeSistemaRequest(App.Infrastructure.HSMService.MantencionDeSistemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MantencionDeSistemaRequestBody {
        
        public MantencionDeSistemaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MantencionDeSistemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MantencionDeSistemaResponse", Namespace="http://www.e-sign.cl/", Order=0)]
        public App.Infrastructure.HSMService.MantencionDeSistemaResponseBody Body;
        
        public MantencionDeSistemaResponse() {
        }
        
        public MantencionDeSistemaResponse(App.Infrastructure.HSMService.MantencionDeSistemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.e-sign.cl/")]
    public partial class MantencionDeSistemaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MantencionDeSistemaResult;
        
        public MantencionDeSistemaResponseBody() {
        }
        
        public MantencionDeSistemaResponseBody(string MantencionDeSistemaResult) {
            this.MantencionDeSistemaResult = MantencionDeSistemaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSIntercambiaDocSoapChannel : App.Infrastructure.HSMService.WSIntercambiaDocSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSIntercambiaDocSoapClient : System.ServiceModel.ClientBase<App.Infrastructure.HSMService.WSIntercambiaDocSoap>, App.Infrastructure.HSMService.WSIntercambiaDocSoap {
        
        public WSIntercambiaDocSoapClient() {
        }
        
        public WSIntercambiaDocSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSIntercambiaDocSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntercambiaDocSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntercambiaDocSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Infrastructure.HSMService.IntercambiaDocResponse App.Infrastructure.HSMService.WSIntercambiaDocSoap.IntercambiaDoc(App.Infrastructure.HSMService.IntercambiaDocRequest request) {
            return base.Channel.IntercambiaDoc(request);
        }
        
        public App.Infrastructure.HSMService.EncabezadoResponse IntercambiaDoc(App.Infrastructure.HSMService.EncabezadoRequest Encabezado, App.Infrastructure.HSMService.DocumentoParametro Parametro) {
            App.Infrastructure.HSMService.IntercambiaDocRequest inValue = new App.Infrastructure.HSMService.IntercambiaDocRequest();
            inValue.Body = new App.Infrastructure.HSMService.IntercambiaDocRequestBody();
            inValue.Body.Encabezado = Encabezado;
            inValue.Body.Parametro = Parametro;
            App.Infrastructure.HSMService.IntercambiaDocResponse retVal = ((App.Infrastructure.HSMService.WSIntercambiaDocSoap)(this)).IntercambiaDoc(inValue);
            return retVal.Body.IntercambiaDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Infrastructure.HSMService.IntercambiaDocResponse> App.Infrastructure.HSMService.WSIntercambiaDocSoap.IntercambiaDocAsync(App.Infrastructure.HSMService.IntercambiaDocRequest request) {
            return base.Channel.IntercambiaDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Infrastructure.HSMService.IntercambiaDocResponse> IntercambiaDocAsync(App.Infrastructure.HSMService.EncabezadoRequest Encabezado, App.Infrastructure.HSMService.DocumentoParametro Parametro) {
            App.Infrastructure.HSMService.IntercambiaDocRequest inValue = new App.Infrastructure.HSMService.IntercambiaDocRequest();
            inValue.Body = new App.Infrastructure.HSMService.IntercambiaDocRequestBody();
            inValue.Body.Encabezado = Encabezado;
            inValue.Body.Parametro = Parametro;
            return ((App.Infrastructure.HSMService.WSIntercambiaDocSoap)(this)).IntercambiaDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Infrastructure.HSMService.MantencionDeSistemaResponse App.Infrastructure.HSMService.WSIntercambiaDocSoap.MantencionDeSistema(App.Infrastructure.HSMService.MantencionDeSistemaRequest request) {
            return base.Channel.MantencionDeSistema(request);
        }
        
        public string MantencionDeSistema() {
            App.Infrastructure.HSMService.MantencionDeSistemaRequest inValue = new App.Infrastructure.HSMService.MantencionDeSistemaRequest();
            inValue.Body = new App.Infrastructure.HSMService.MantencionDeSistemaRequestBody();
            App.Infrastructure.HSMService.MantencionDeSistemaResponse retVal = ((App.Infrastructure.HSMService.WSIntercambiaDocSoap)(this)).MantencionDeSistema(inValue);
            return retVal.Body.MantencionDeSistemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Infrastructure.HSMService.MantencionDeSistemaResponse> App.Infrastructure.HSMService.WSIntercambiaDocSoap.MantencionDeSistemaAsync(App.Infrastructure.HSMService.MantencionDeSistemaRequest request) {
            return base.Channel.MantencionDeSistemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Infrastructure.HSMService.MantencionDeSistemaResponse> MantencionDeSistemaAsync() {
            App.Infrastructure.HSMService.MantencionDeSistemaRequest inValue = new App.Infrastructure.HSMService.MantencionDeSistemaRequest();
            inValue.Body = new App.Infrastructure.HSMService.MantencionDeSistemaRequestBody();
            return ((App.Infrastructure.HSMService.WSIntercambiaDocSoap)(this)).MantencionDeSistemaAsync(inValue);
        }
    }
}
